name: runner
description: A client that sends code to the parser and receives and AST.
dependencies:
  json_rpc_2: any
  shelf: any
  shelf_web_socket: any
  iclc_config:
    path: ../config
  iclc_exec:
    path: ../exec
  ops_intrinsics_replacer:
    path: ../ops-intrinsics-replacer
